<?php

/**
 * @file
 * Module for site studio webform.
 */

use Drupal\webform\WebformInterface;
use Drupal\node\Entity\Node;

/**
 * @file
 * Provides Site Studio Webform element.
 */

/**
 * Implements hook_theme().
 */
function site_studio_webform_theme($existing, $type, $theme, $path) {
  return [
    'site_studio_webform_node_element_template' => [
      'variables' => [
        'elementSettings' => NULL,
        'elementMarkup' => NULL,
        'elementClass' => NULL,
        'webform' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function site_studio_webform_webform_insert(WebformInterface $webform) {
  $node = Node::create([
    'type' => 'webform',
    'title' => $webform->label(),
    'webform' => ['target_id' => $webform->id()],
  ]);
  $node->save();

  \Drupal::messenger()->addMessage(t('Node %label created.', ['%label' => $node->label()]));
}

/**
 * Implements hook_entity_bundle_delete().
 */
function site_studio_webform_webform_delete(WebformInterface $webform) {
  // Get the webform node id which has the deleted webform instance
  $node = \Drupal::entityQuery('node')
                ->condition('type', 'webform')
                ->condition('title', $webform->label(), '=')
                ->condition('webform', $webform->id())
                ->execute();

  if($node) {
    foreach ($node as $id) {
      $node_obj = Node::load($id);
      $node_obj->delete();
    }
  }

  \Drupal::messenger()->addMessage(t('Node %label deleted.', ['%label' => $node_obj->label()]));
}
